FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/bot/ ./cmd/bot/
COPY internal/ ./internal/
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o bot ./cmd/bot

FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /app/bot /bot
COPY .env /app/.env
CMD ["/bot"]