FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/parser/ ./cmd/parser/
COPY internal/ ./internal/
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o parser ./cmd/parser/main.go
FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /app/parser /parser
COPY .env /app/.env
CMD ["/parser"]